// Collect redistribution notices from the exact installed/locked dependencies.
import { execFileSync } from "node:child_process";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
async function licenses(directory) {
  const files = (await readdir(directory))
    .filter((name) => /^(licen[cs]e|copying|notice)([._-]|$)/i.test(name))
    .sort();
  const sections = [];
  for (const name of files) {
    try {
      sections.push(
        `${name}\n${(await readFile(resolve(directory, name), "utf8")).trim()}`,
      );
    } catch (error) {
      if (error.code !== "EISDIR") throw error;
    }
  }
  if (!sections.length)
    throw new Error(`No license notice found in ${directory}`);
  return sections.join("\n\n");
}
for (const project of ["web", "action"]) {
  const lock = JSON.parse(
    await readFile(resolve(root, project, "package-lock.json"), "utf8"),
  );
  const sections = [
    `Third-party notices for CIVault ${project}. Generated by scripts/notices.mjs.\n`,
  ];
  for (const [path, pkg] of Object.entries(lock.packages).sort(([a], [b]) =>
    a.localeCompare(b, "en"),
  )) {
    if (!path || pkg.dev) continue;
    sections.push(
      `${path.replace(/^node_modules\//, "")} ${pkg.version}\n${"=".repeat(72)}\n${await licenses(resolve(root, project, path))}`,
    );
  }
  await writeFile(
    resolve(root, "docs", `THIRD_PARTY_${project.toUpperCase()}_NOTICES.txt`),
    sections.join("\n\n") + "\n",
  );
}
const lines = execFileSync(
  "go",
  ["list", "-m", "-f", "{{.Path}}|{{.Version}}|{{.Dir}}", "all"],
  { cwd: root, encoding: "utf8", windowsHide: true },
)
  .trim()
  .split(/\r?\n/);
const sections = [
  "Third-party notices for CIVault Go binaries. Generated by scripts/notices.mjs.\n",
];
const goroot = execFileSync("go", ["env", "GOROOT"], {
  cwd: root,
  encoding: "utf8",
  windowsHide: true,
}).trim();
sections.push(
  `Go standard library\n${"=".repeat(72)}\n${await licenses(goroot)}`,
);
for (const line of lines) {
  const [name, version, dir] = line.split("|");
  if (!version || !dir) continue;
  sections.push(
    `${name} ${version}\n${"=".repeat(72)}\n${await licenses(dir)}`,
  );
}
await writeFile(
  resolve(root, "docs/THIRD_PARTY_GO_NOTICES.txt"),
  sections.join("\n\n") + "\n",
);
